Wait for ICMP_ECHOREPLY packet alive with epoll
matsumotory/mruby-fast-remote-check pull request #8
Opened 2018-06-08 15:56 UTC by takumakume

https://github.com/matsumotory/mruby-fast-remote-check/pull/7 のPRの修正版として、以下のように問題の特定と修正を行いました。

### 発生した問題

同時に単一のsocket上で複数のIPアドレスに ICMP Echo Reqest を送信した場合に最初の ICMP Echo Reply の到着によって、本来別のIPアドレスからの Reply を待つプロセスもrecv後、リトライすることなく `false` を返してしまう。

### 再現テスト手順と結果の説明

#### 再現手順

今回は分かりやすいように以下のようなコードを挿入してPrintデバッグを実施しました。
https://github.com/takumakume/mruby-fast-remote-check/commit/a146830368c0ad604e6208765af13e3d97e7e013

1. テストコード (test.rb)

  ```ruby
  ip = ARGV[0]
  puts " ==> #{ip} #{FastRemoteCheck::ICMP.new(ip, 3).ping?}"
  ```

2. tcpdumpによりICMPパケットの収集

  ```
  tcpdump -s0 -nn -w tcpdump_$(date +%Y%m%d%H%M%S).cap icmp
  ```

3. テストコードを並行で実行

  ```sh
  echo "8.8.8.8
  1.1.1.1" | xargs -P 2 -L 1 strace -Ttt -ff -s 1500000 -o strace_$(date +%Y%m%d%H%M%S) mruby/bin/mruby ~/test.rb
  ```

#### 結果

以下にtcpdumpの結果と、straceの結果を時系列に並べて説明する。

```sh
# ソケットを(4)で作成
15:31:18.865712 [8.8.8.8] socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 4 <0.000033>
15:31:18.865771 [8.8.8.8] setsockopt(4, SOL_SOCKET, SO_RCVTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000009>
15:31:18.865802 [8.8.8.8] setsockopt(4, SOL_SOCKET, SO_SNDTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000008>
# 8.8.8.8へICMPを送付
15:31:18.865831 [8.8.8.8] sendto(4, "\10\0\367\377\0\0\0\0", 8, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("8.8.8.8")}, 16) = 8 <0.000120>
# 8.8.8.8へのICMP echoが送信される
15:31:18.865912 [tcpdump] IP server > 8.8.8.8: ICMP echo request, id 0, seq 0, length 8
# recvを開始 (ブロッキング)
15:31:18.866035 [8.8.8.8] recvfrom(4, "E\0\0\34\342\244@\0?\1=\36\10\10\10\10\n\0\2\17\0\0\377\377\0\0\0\0", 1500, 0, NULL, NULL) = 28 <0.022840>

# 別プロセスでソケットを(4)で作成
15:31:18.868766 [1.1.1.1] socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 4 <0.000035>
15:31:18.868824 [1.1.1.1] setsockopt(4, SOL_SOCKET, SO_RCVTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000009>
15:31:18.868855 [1.1.1.1] setsockopt(4, SOL_SOCKET, SO_SNDTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000008>
# 1.1.1.1へICMPを送付
15:31:18.868882 [1.1.1.1] sendto(4, "\10\0\367\377\0\0\0\0", 8, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("1.1.1.1")}, 16) = 8 <0.000106>
# 1.1.1.1へのICMP echoが送信される
15:31:18.868916 [tcpdump] IP server > 1.1.1.1: ICMP echo request, id 0, seq 0, length 8
# recvを開始 (ブロッキング)
15:31:18.869023 [1.1.1.1] recvfrom(4, "E\0\0\34\342\244@\0?\1=\36\10\10\10\10\n\0\2\17\0\0\377\377\0\0\0\0", 1500, 0, NULL, NULL) = 28 <0.019892>

# 8.8.8.8からのICMP echo replyが到着
# ここで2つの recvfrom が受け取る
15:31:18.888700 [tcpdump] IP 8.8.8.8 > server: ICMP echo reply, id 0, seq 0, length 8

15:31:18.888953 [8.8.8.8] fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0 <0.000014>
15:31:18.889005 [1.1.1.1] fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0 <0.000189>
15:31:18.889065 [8.8.8.8] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcc6e79c000 <0.000018>

# 8.8.8.8からのICMP echo replyが到着
# socketには入るが、recvはもう起きない
15:31:18.889147 [tcpdump] IP 1.1.1.1 > server: ICMP echo reply, id 0, seq 0, length 8
15:31:18.889194 [8.8.8.8] close(4)                = 0 <0.000023>

15:31:18.889249 [1.1.1.1] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe205c47000 <0.000014>

# 8.8.8.8からのreplyをrecvしているので True
15:31:18.889270 [8.8.8.8] write(1, "data->dst_ip, recv_iphdr->saddr : 134744072, 134744072 ==> 8.8.8.8 true", 71) = 71 <0.000269>

15:31:18.889308 [1.1.1.1] close(4)                = 0 <0.000017>

# 8.8.8.8からのreplyをrecvしているので False
15:31:18.889367 [1.1.1.1] write(1, "data->dst_ip, recv_iphdr->saddr : 16843009, 134744072 ==> 1.1.1.1 false", 71) = 71 <0.000017>
```

### 本PRの解決手法

- これまで通りにrecv後に、ICMPパケットのチェック処理を行う。そこで、チェックが通らない場合は再度recv待機する。
- epollを使って、socketを監視してrecvをリトライする。タイムアウトもepollで行う。

### 同様のテスト手順の確認結果

`本PRの解決手法` で示した意図通りに動作している。

```sh
23:41:17.395409 [8.8.8.8] socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 4 <0.000039>
23:41:17.395472 [8.8.8.8] setsockopt(4, SOL_SOCKET, SO_RCVTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000011>
23:41:17.395508 [8.8.8.8] setsockopt(4, SOL_SOCKET, SO_SNDTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000007>
23:41:17.395536 [8.8.8.8] sendto(4, "\10\0\367\377\0\0\0\0", 8, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("8.8.8.8")}, 16) = 8 <0.000277>
23:41:17.395573 [tcpdump] IP server > 8.8.8.8: ICMP echo request, id 0, seq 0, length 8
23:41:17.395862 [8.8.8.8] epoll_create(1)         = 5 <0.000014>
23:41:17.395906 [8.8.8.8] epoll_ctl(5, EPOLL_CTL_ADD, 4, {EPOLLIN, {u32=4, u64=4642859646980}}) = 0 <0.000009>
23:41:17.395943 [8.8.8.8] epoll_wait(5, [{EPOLLIN, {u32=4, u64=4642859646980}}], 1, 3000) = 1 <0.035051>
23:41:17.396938 [1.1.1.1] socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 4 <0.000040>
23:41:17.397017 [1.1.1.1] setsockopt(4, SOL_SOCKET, SO_RCVTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000009>
23:41:17.397045 [1.1.1.1] setsockopt(4, SOL_SOCKET, SO_SNDTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000007>
23:41:17.397070 [1.1.1.1] sendto(4, "\10\0\367\377\0\0\0\0", 8, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("1.1.1.1")}, 16) = 8 <0.000154>
23:41:17.397106 [tcpdump] IP server > 1.1.1.1: ICMP echo request, id 0, seq 0, length 8
23:41:17.397268 [1.1.1.1] epoll_create(1)         = 5 <0.000013>
23:41:17.397308 [1.1.1.1] epoll_ctl(5, EPOLL_CTL_ADD, 4, {EPOLLIN, {u32=4, u64=9266893077904097284}}) = 0 <0.000008>
23:41:17.397338 [1.1.1.1] epoll_wait(5, [{EPOLLIN, {u32=4, u64=9266893077904097284}}], 1, 3000) = 1 <0.033591>
23:41:17.430764 [tcpdump] IP 8.8.8.8 > server: ICMP echo reply, id 0, seq 0, length 8
23:41:17.431053 [1.1.1.1] recvfrom(4, "E\0\0\34V~@\0?\1\311D\10\10\10\10\n\0\2\17\0\0\377\377\0\0\0\0", 1500, MSG_DONTWAIT, NULL, NULL) = 28 <0.000012>
23:41:17.431053 [8.8.8.8] recvfrom(4, "E\0\0\34V~@\0?\1\311D\10\10\10\10\n\0\2\17\0\0\377\377\0\0\0\0", 1500, MSG_DONTWAIT, NULL, NULL) = 28 <0.000012>
# ここで、別のIPアドレスからのリプライのため再度epollで待つ
23:41:17.431110 [1.1.1.1] epoll_wait(5, [{EPOLLIN, {u32=4, u64=9266893077904097284}}], 1, 3000) = 1 <0.013761>
23:41:17.431118 [8.8.8.8] close(5)                = 0 <0.000015>
23:41:17.431154 [8.8.8.8] close(4)                = 0 <0.000062>
23:41:17.431312 [8.8.8.8] fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 2), ...}) = 0 <0.000009>
23:41:17.431356 [8.8.8.8] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f05bec9a000 <0.000012>
23:41:17.431394 [8.8.8.8] write(1, " ==> 8.8.8.8 true", 17) = 17 <0.000226>
23:41:17.431764 [8.8.8.8] write(1, "\n", 1)       = 1 <0.000207>
23:41:17.432026 [8.8.8.8] close(3)                = 0 <0.000012>
23:41:17.432060 [8.8.8.8] munmap(0x7f05bec9b000, 4096) = 0 <0.000019>
23:41:17.432215 [8.8.8.8] exit_group(0)           = ?
23:41:17.432334 [8.8.8.8] +++ exited with 0 +++
23:41:17.444778 [tcpdump] IP 1.1.1.1 > server: ICMP echo reply, id 0, seq 0, length 8
23:41:17.444939 [1.1.1.1] recvfrom(4, "E\0\0\34V\201@\0?\1\327O\1\1\1\1\n\0\2\17\0\0\377\377\0\0\0\0", 1500, MSG_DONTWAIT, NULL, NULL) = 28 <0.000014>
23:41:17.445033 [1.1.1.1] close(5)                = 0 <0.000014>
23:41:17.445070 [1.1.1.1] close(4)                = 0 <0.000019>
23:41:17.445137 [1.1.1.1] fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 2), ...}) = 0 <0.000010>
23:41:17.445177 [1.1.1.1] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7d830ed000 <0.000016>
23:41:17.445228 [1.1.1.1] write(1, " ==> 1.1.1.1 true", 17) = 17 <0.000032>
23:41:17.445300 [1.1.1.1] write(1, "\n", 1)       = 1 <0.000078>
23:41:17.445422 [1.1.1.1] close(3)                = 0 <0.000012>
23:41:17.445456 [1.1.1.1] munmap(0x7f7d830ee000, 4096) = 0 <0.000022>
23:41:17.445669 [1.1.1.1] exit_group(0)           = ?
23:41:17.445904 [1.1.1.1] +++ exited with 0 +++
```

なお、epollで待つ動作のためCPU専有はしない。

```sh
# time mruby/bin/mruby -e 'p FastRemoteCheck::ICMP.new("1.255.255.255", 3).ping?'
trace (most recent call last):
	[0] -e:1
-e:1: sys failed. errno: 0 message: S [...]

2018-06-08 16:09 UTC, matsumotory commented
ひとまずテストコードは書いてください。その上で、これをepoll+nonblock recvで使ってやっている理由がよくわかりませんでした。ブロッキングrecvだけでループにしたらだめなんでしょうか？

2018-06-09 06:55 UTC, takumakume commented
> ひとまずテストコードは書いてください。

承知しました。

> epoll+nonblock recvで使ってやっている理由がよくわかりませんでした。ブロッキングrecvだけでループにしたらだめなんでしょうか？

再度検証したところ、recvだけで良かったです。検証当時にnon-blockingを外し忘れていて、大量にloopしてしまったのに気づいておらずepollが必要と錯覚していました。

2018-06-09 07:17 UTC, takumakume commented
テストのみコミットした状態で手元ではテストがFailすることを確認しました。

```
Fail: FastRemoteCheck::ICMP#ping? for wait packet reply (mrbgems: mruby-fast-remote-check)
 - Assertion[1] Failed: Expected true to be false
    Expected: false
      Actual: true
```

2018-06-09 09:47 UTC, takumakume commented
@matsumotory

CIの環境ではテストのFailが再現しませんが、以下の仮想マシン環境にて再現します。

- OS: CentOS7
  - CPU: 2
  - Mem: 2GB

- OS: CentOS7
  - CPU: 1
  - Mem: 2GB

以下の修正を加えました。

- 同時に単一のsocket上で複数のIPアドレスに ICMP Echo Reqest を送信した場合に最初の ICMP Echo Reply の到着によって、本来別のIPアドレスからの Reply を待つプロセスもrecv後、リトライすることなく `false` を返してしまう状況のテストコードを作成。
- recvをループしてReplyを受け取る。

以下のように意図する通りに動作することを確認しました。

```sh
03:16:49.200677 [8.8.8.8] socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 4 <0.000752>
03:16:49.201502 [8.8.8.8] setsockopt(4, SOL_SOCKET, SO_RCVTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000018>
03:16:49.201631 [8.8.8.8] setsockopt(4, SOL_SOCKET, SO_SNDTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000013>
03:16:49.201683 [8.8.8.8] sendto(4, "\10\0\367\377\0\0\0\0", 8, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("8.8.8.8")}, 16) = 8 <0.000140>
03:16:49.201816 [tcpdump] IP server > 8.8.8.8: ICMP echo request, id 0, seq 0, length 8
03:16:49.201956 [8.8.8.8] recvfrom(4, "E\0\0\34S\216@\0?\1\3144\10\10\10\10\n\0\2\17\0\0\377\377\0\0\0\0", 1500, 0, NULL, NULL) = 28 <0.028105>
03:16:49.204373 [1.1.1.1] socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 4 <0.000060>
03:16:49.204474 [1.1.1.1] setsockopt(4, SOL_SOCKET, SO_RCVTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000014>
03:16:49.204527 [1.1.1.1] setsockopt(4, SOL_SOCKET, SO_SNDTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0 <0.000018>
03:16:49.204675 [1.1.1.1] sendto(4, "\10\0\367\377\0\0\0\0", 8, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("1.1.1.1")}, 16) = 8 <0.000418>
03:16:49.204909 [tcpdump] IP server > 1.1.1.1: ICMP echo request, id 0, seq 0, length 8
03:16:49.205285 [1.1.1.1] recvfrom(4, "E\0\0\34S\216@\0?\1\3144\10\10\10\10\n\0\2\17\0\0\377\377\0\0\0\0", 1500, 0, NULL, NULL) = 28 <0.024746>
03:16:49.229861 [tcpdump] IP 8.8.8.8 > server: ICMP echo reply, id 0, seq 0, length 8
# 再度recvすることで1.1.1.1からのreplyを受け取る準備をする。
03:16:49.230186 [1.1.1.1] recvfrom(4, "E\0\0\34S\221@\0?\1\332?\1\1\1\1\n\0\2\17\0\0\377\377\0\0\0\0", 1500, 0, NULL, NULL) = 28 <0.022565>
03:16:49.230192 [8.8.8.8] close(4)                = 0 <0.000022>
03:16:49.230280 [8.8.8.8] fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 2), ...}) = 0 <0.000009>
03:16:49.230313 [8.8.8.8] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d25098000 <0.000012>
03:16:49.230354 [8.8.8.8] write(1, " ==> 8.8.8.8 true", 17) = 17 <0.000236>
03:16:49.230629 [8.8.8.8] write(1, "\n", 1)       = 1 <0.000122>
03:16:49.230797 [8.8.8.8] close(3)                = 0 <0.000014>
03:16:49.230834 [8.8.8.8] munmap(0x7f1d25099000, 4096) = 0 <0.000023>
03:16:49.231020 [8.8.8.8] exit_group(0)           = ?
03:16:49.231182 [8.8.8.8] +++ exited with 0 +++
03:16:49.252533 [tcpdump] IP 1.1.1.1 > server: ICMP echo reply, id 0, seq 0, length 8
03:16:49.252958 [1.1.1.1] close(4)                = 0 <0.000027>
03:16:49.253076 [1.1.1.1] fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 2), ...}) = 0 <0.000010>
03:16:49.253111 [1.1.1.1] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7c4f18b000 <0.000015>
03:16:49.253158 [1.1.1.1] write(1, " ==> 1.1.1.1 true", 17) = 17 <0.000042>
03:16:49.253289 [1.1.1.1] write(1, "\n", 1)       = 1 <0.000014>
03:16:49.253349 [1.1.1.1] close(3)                = 0 <0.000013>
03:16:49.253385 [1.1.1.1] munmap(0x7f7c4f18c000, 4096) = 0 <0.000021>
03:16:49.253798 [1.1.1.1] exit_group(0)           = ?
03:16:49.253951 [1.1.1.1] +++ exited with 0 +++
```

recvのブロッキングによりwaitするためCPU専有はなし。

```sh
# time mruby/bin/mruby -e 'p FastRemoteCheck::ICMP.new("1.255.255.255", 3).ping?'
trace (most recent call last):
	[0] -e:1
-e:1: sys failed. errno: 11 message: Resource temporarily unavailable mrbgem message: recv timeout (RuntimeError)

real	0m3.056s
user	0m0.002s
sys	0m0.002s
```

再度、ご確認をお願いいたします。

2018-06-09 09:53 UTC, matsumotory commented
> CIの環境ではFailしない

コードをレビューする前に、

- バグの再現性のあるテストを書く
- それが再現性があることをCIのような汎用性のある場所で示す
- その上でパッチによりそのテストが通ることを示す

ことが重要なので、手元では、というのでは客観的な議論になりません。コードで示しましょう。

CIにて再現のあるバグをテストで示し、その上で議論を組み立ててください。現状では、久米さんの手元では起きるんだろう以上のコメントになっていないように感じます。

2018-06-09 10:23 UTC, takumakume commented
> 客観的な議論

はい、承知いたしました。テストを修正します。

2018-06-09 10:42 UTC, takumakume commented
以下のようにCI環境でテストがFailすることができました。
https://travis-ci.org/takumakume/mruby-fast-remote-check/jobs/390077161#L819

今回の修正を加えて、Passすることも確認いたしました。
ご確認をよろしくお願いいたします。

2018-06-09 11:01 UTC, matsumotory requested changes

2018-06-09 11:01 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  th << Thread.new { FastRemoteCheck::ICMP.new("1.1.1.5", 3).ping? }
ここまで沢山スレッドを用意しなくても、他のテストで使っているようなunreachableなipアドレスに対して、タイムアウトを長めにした上でpingを送り、reachableなipにpingを送れば再現するように思いますがどうでしょう？

2018-06-09 11:01 UTC, matsumotory commented on src/mrb_fastremotecheck.c
> +      }
タイムアウトをソケットとは別に用意してチェックするの、シンプルで良い実装ですね。

2018-06-09 11:01 UTC, matsumotory commented
実装はOKです！テストはもう少しシンプルにかけると思うのでそこだけ指摘しました。

2018-06-09 11:12 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  th << Thread.new { FastRemoteCheck::ICMP.new("1.1.1.5", 3).ping? }
より厳密には、そのようにスレッドで並行してpingしても、unreacheableなスレッドはassert_raise、reachableなスレッドばassert_trueすることをしめせばよいでしょう

2018-06-09 11:52 UTC, takumakume commented on test/mrb_fastremotecheck.rb
> +  th << Thread.new { FastRemoteCheck::ICMP.new("1.1.1.5", 3).ping? }
> unreacheableなスレッドはassert_raise、reachableなスレッドばassert_true

なるほど、そう思いますのでテストを修正します。

2018-06-09 13:06 UTC, takumakume commented on test/mrb_fastremotecheck.rb
> +  th << Thread.new { FastRemoteCheck::ICMP.new("1.1.1.5", 3).ping? }
こちらのコミットにて修正しました。 https://github.com/matsumotory/mruby-fast-remote-check/pull/8/commits/dd75c18bec3448e350af40e23014e203cd4807b4

1. `1.1.1.1` のpingはreplyを受け取るため `true`
2. `203.0.113.1` のpingは `1.1.1.1` のパケットを参照するため `false` (masterブランチだと)
3. `8.8.8.8` のpingは `1.1.1.1` のパケットを参照するため `false` (masterブランチだと)

という内容です。

以下のように、masterブランチの状態であればテストがFailすることを確認しています。

  - commit: https://github.com/takumakume/mruby-fast-remote-check/commits/test
  - test: https://travis-ci.org/takumakume/mruby-fast-remote-check/jobs/390109275#L819

2018-06-09 13:09 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  th << Thread.new { FastRemoteCheck::ICMP.new("1.1.1.5", 3).ping? }
2.と3.だけじゃだめな理由はなんですか？

2018-06-09 13:11 UTC, pyama86 commented
余談ですが、この手の必ず落ちるpingみたいなのはdocument ip使ったほうが良さそう。
https://tools.ietf.org/html/rfc5737
```
3.  Documentation Address Blocks

   The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2),
   and 203.0.113.0/24 (TEST-NET-3) are provided for use in
   documentation.
```

2018-06-09 13:13 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  th << Thread.new { FastRemoteCheck::ICMP.new("1.1.1.5", 3).ping? }
今回のバグの根本的な理由は、とあるpingの戻り待ちに、別のpingの戻りが重なった場合に、元のpingがfalseしてしまうことだと思います。その場合、わざわざ1と3のような、タイミング次第ではテストが通るかどうかわからないような不確かなテストを追加するよりは、明確に2と3で確実に落ちるipアドレスと通るipアドレスで再現したほうが根本原因を示すテストになるように思います。

2018-06-09 13:15 UTC, matsumotory commented
pyama++

2018-06-09 13:35 UTC, takumakume commented on test/mrb_fastremotecheck.rb
> +  th << Thread.new { FastRemoteCheck::ICMP.new("1.1.1.5", 3).ping? }
> 2.と3.だけじゃだめな理由はなんですか？

raiseのパターンとtrueのパターンで不必要にどちらもテストを書いておりました。おっしゃる通り `2` と `3` で実装し直します。

2018-06-09 13:42 UTC, takumakume commented
> document ip

なるほど、これは知りませんでした。コード中にあった `203.0.113.` はそれだったのですね。逆に絶対通るIPで `8.8.8.8` にしていたところは `127.0.01` に変更しました。

2018-06-09 13:44 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  t1 = Thread.new { FastRemoteCheck::ICMP.new("203.0.113.1", 5).ping? rescue "raised" }
これはmruby-threadでraiseを直接拾えなかった感じですか？

2018-06-09 13:46 UTC, takumakume commented on test/mrb_fastremotecheck.rb
> +  t1 = Thread.new { FastRemoteCheck::ICMP.new("203.0.113.1", 5).ping? rescue "raised" }
はい、その通りです。

2018-06-09 13:46 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  t1 = Thread.new { FastRemoteCheck::ICMP.new("203.0.113.1", 5).ping? rescue "raised" }
なぜだろう？逆にいうとどんなコードで試しましたか？

2018-06-09 13:47 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  t1 = Thread.new { FastRemoteCheck::ICMP.new("203.0.113.1", 5).ping? rescue "raised" }
こういう意図みたいなのはcommit logなりコメントなりでちゃんと示すようにしてください。

2018-06-09 13:56 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  t1 = Thread.new { FastRemoteCheck::ICMP.new("203.0.113.1", 5).ping? rescue "raised" }
threadでjoinした後に、thread内で例外が起きた場合は、joinの返り値に例外オブジェクトが返ってきているように思えます。その例外オブジェクトを使ったテストに書き換えてみてください。

2018-06-09 14:02 UTC, matsumotory commented on test/mrb_fastremotecheck.rb
> +  t1 = Thread.new { FastRemoteCheck::ICMP.new("203.0.113.1", 5).ping? rescue "raised" }
```
$ ./bin/mirb 
mirb - Embeddable Interactive Ruby Shell

> Thread.new { 1*nil }.join.class == TypeError
 => true
```

2018-06-09 14:09 UTC, takumakume commented on test/mrb_fastremotecheck.rb
> +  t1 = Thread.new { FastRemoteCheck::ICMP.new("203.0.113.1", 5).ping? rescue "raised" }
ありがとうございます。例外オブジェクトを捕捉することができました。

2018-06-09 14:14 UTC, matsumotory commented
lgtm! 繰り返しになりますが、

- バグをテストコードで客観的に示す
  - その際にはテストに複数の意図や振る舞いを混ぜない
- パッチを当てることでそのテストが通るようになる（これによって同じミスを今後も踏まない）
- 環境に依存したバグによる不要な議論をなくすためにCI環境で客観的に示す
- なにかうまくいかなかったときに、こうやったらうまくいった、までではなく、そこからなぜうまくいかなかったかの調査をちゃんとする（今回でいうスレッドの例外オブジェクトなど）

ということをしっかり意識すると良いと思います！

2018-06-09 14:14 UTC, matsumotory approved these changes

2018-06-09 14:14 UTC, merged

2018-06-09 14:15 UTC, takumakume commented
ご確認、ご教示いただきありがとうございました。